swagger: "2.0"
info:
  description: This swagger described the operation of the APIs 
  title: Swagger REST alertCOVID19
  version: "1.0.0"
  contact:
    email: "jeanbaptiste.gandonou@gmail.com | fhoueha@gmail.com | sidoux05@gmail.com"
  license:
    name: "Francis Jean-Baptiste Sidoine"
    url: "contact@gmail.com"
  
consumes:
  - application/json
produces:
  - application/json
basePath: /api

# Paths supported by the server application
paths:
# scrap_api
  /scrap_api:
    post:
      operationId: scrap_api.scrappingAndSave
      tags:
        - scrap_api
      summary: Save  card information
      description: Save  card information
      responses:
        200:
          description: Successfully to save produit
          schema:
            properties:
              covidstatic:
                type: string
                description: 1 for Successfully other for mistake

  /scrap_api/getOne:
    get:
      operationId: scrap_api.getOne
      tags:
        - scrap_api
      summary: Get  covid stat
      description: Get  covid stat
      responses:
        201:
          description: Successfully to get esv template
          schema:
            properties:
              templatedescription:
                type: string
                description: esv template description
              templatename:
                type: string
                description: esv template name
              grouptemplate:
                type: string
                description: esv template
    
  #
# actualite_scrap
  /actualite_scrap:
    post:
      operationId: actualite_scrap.scrappingActualiteAndSave
      tags:
        - actualite_scrap
      summary: Save  card information
      description: Save  card information
      responses:
        200:
          description: Successfully to save produit
          schema:
            properties:
              covidstatic:
                type: string
                description: 1 for Successfully other for mistake

  /actualite_scrap/create:
    post:
      operationId: actualite_scrap.createTable
      tags:
        - actualite_scrap
      summary: Save  card information
      description: Save  card information
      responses:
        200:
          description: Successfully to save produit
          schema:
            properties:
              covidstatic:
                type: string
                description: 1 for Successfully other for mistake

  /actualite_scrap/getActualite:
    get:
      operationId: actualite_scrap.getAllActualite
      tags:
        - actualite_scrap
      summary: Get  covid stat
      description: Get  covid stat
      responses:
        201:
          description: Successfully to get esv template
          schema:
            properties:
              templatedescription:
                type: string
                description: esv template description
    
# mapDb

  # /mapDb/{longitude}/{latitude}/{mapdate}/{numeroTel}:
  #   post:
  #     operationId: mapDb.addMapDb
  #     tags:
  #       - mapDb
  #     summary: Save  veda table
  #     description: Save  veda table
  #     parameters:
  #       - name: longitude
  #         in: path
  #         description: codeoftable
  #         type: string
  #         required: True
  #       - name: latitude
  #         in: path
  #         description: codeoftable
  #         type: string
  #         required: True
  #       - name: mapdate
  #         in: path
  #         description: codeoftable
  #         type: string
  #         required: True
  #       - name: numeroTel
  #         in: path
  #         description: codeoftable
  #         type: string
  #         required: True         
  #     responses:
  #       201:
  #         description: Successfully created veda db
  #         schema:
  #           properties:
  #             import_id:
  #               type: string
  #               description: Id of import

  /mapDb/getmapDb:
    get:
      operationId: mapDb.getAllMapDb
      tags:
        - mapDb
      summary: Get  covid stat
      description: Get  covid stat
      responses:
        201:
          description: Successfully to get esv template
          schema:
            properties:
              templatedescription:
                type: string
                description: esv template description

  /mapDb/create:
    post:
      operationId: mapDb.addMapDb
      tags:
        - mapDb
      summary: Create eUser
      description: Create eUser
      parameters:
        - name: data
          in: body
          description: eUser
          schema:
            type: object
            properties:
              longitude:
                type: string
                description: name of USer
              latitude:
                type: string
                description: prenom of User
              mapdate:
                type: string
                description: Mail of User
              numeroTel:
                type: string
                description: Tel of User
      responses:
        201:
          description: Successfully created veda db
          schema:
            properties:
              import_id:
                type: string
                description: Id of import